name: WieIsDeMol
version: '${version}'
main: nl.mxndarijn.cluedo.Cluedo
api-version: 1.19
depend: [ ProtocolLib, PlaceholderAPI, TAB]
softdepend: [ SuperVanish]
commands:
  test:
    Description: Test command for development
    usage: /test
  maps:
    description: maps
    usage: /maps
  presets:
    description: presets
    usage: /presets
  items:
    description: Items
    usage: /items
  skulls:
    description: Custom heads
    usage: /skulls
    aliases:
      - skulls
      - skull
      - head
      - heads
      - heads-database
  spawn:
    description: Spawn
    usage: /spawn
  ms:
    description: Message Speler
    usage: /ms [Speler] [Bericht]
    aliases:
      - ms
      - messagespeler
      - messageplayer
  modify:
    descriptiuon: Modify
    usage: /modify
  togglescoreboard:
    description: Toggle your scoreboard
    usage: /togglescoreboard
    aliases:
      - ts
      - toggles
      - togglescoreboard
